spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shirtso
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: db/migration
app:
  security:
    jwt:
      token:
        secret: ac6717b2200890a633458a304da98cb8ebf7c7d3baf21e2e585ba087c8af0ba309ac0f454fec2bd67d64029b6fceb3789166466a1571bf49c65cf71d1c23cd2b
        validity: 60
