spring:
  config:
    import: optional:file:./secrets.properties
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${jpa.ddl-auto}
    show-sql: ${jpa.show-sql}
  flyway:
    locations: db/migration
    schemas: public
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/photos/
  mvc:
    static-path-pattern: /**
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            starttls:
              enable: false
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              port: ${mail.port}
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.peter_lukas.shirtso.auth.jwt.JWTReqFilter: DEBUG
    org.springframework.security: DEBUG

server:
  port: ${server.port}

app:
  frontend:
    url: ${frontend.url}
  password-reset:
    token-validity-hours: ${password.reset.token.validity}
  security:
    jwt:
      token:
        secret: ${jwt.secret}
        validity: ${jwt.validity}
  notification:
    email:
      from: shirtso@lukspeed.eu
      enabled: true
  cors:
    allowed-origins: ${cors.origins}
    allowed-methods: ${cors.methods}
    allowed-headers: ${cors.headers}
    allow-credentials: ${cors.allow-credentials}
    max-age: ${cors.max-age}