### product_spodnie

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 112,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 2,
  "size": "XXXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 562,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 37,
  "size": "XXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 86,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 317,
  "size": "XL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 88,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 107,
  "size": "L"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 62,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 70,
  "size": "M"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 2212,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 9,
  "size": "S"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Jeansy",
  "description": "Dżinsowe spodnie męskie, 'rurki'",
  "price": 519.99,
  "currency": "PLN",
  "imageId": 712,
  "subcategoryId": 18,
  "supplier": "Kros-jeans Polska",
  "stock": 1,
  "size": "XS"
}

### product_sweter

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 9,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 2,
  "size": "XXXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 3,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 10,
  "size": "XXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 4,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 22,
  "size": "XL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 38,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 41,
  "size": "L"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 1,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 58,
  "size": "M"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 16,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 9,
  "size": "S"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Sweter",
  "description": "Bawełniany sweter męski z długim rękawem, dostępny w różnych kolorach.",
  "price": 119.99,
  "currency": "PLN",
  "imageId": 79,
  "subcategoryId": 11,
  "supplier": "Best Clothes Ltd",
  "stock": 17,
  "size": "XS"
}

### product_marynarka
POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 307,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 2,
  "size": "XXXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 308,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 1,
  "size": "XXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 309,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 12,
  "size": "XL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 310,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 6,
  "size": "L"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 311,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 0,
  "size": "M"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 312,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 2,
  "size": "S"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Marynarka",
  "description": "Marynarka męska, bawełniana w 'szkocką kratę', dostępna w różnych kolorach",
  "price": 630.00,
  "currency": "PLN",
  "imageId": 313,
  "subcategoryId": 3,
  "supplier": "Dobler-Fashion",
  "stock": 1,
  "size": "XS"
}

### product_plaszcz

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 43,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 3,
  "size": "XXXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 44,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 1,
  "size": "XXL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 45,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 4,
  "size": "XL"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 46,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 5,
  "size": "L"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 47,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 6,
  "size": "M"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 48,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 3,
  "size": "S"
}

###

POST localhost:8080/api/products
Authorization: Bearer {{auth-token}}
content-type: application/json

{
  "productName": "Płaszcz",
  "description": "Wełniany płaszcz męski do kolan z długim rękawem, dostępny w różnych kolorach.",
  "price": 1119.99,
  "currency": "PLN",
  "imageId": 49,
  "subcategoryId": 2,
  "supplier": "Bytomianka",
  "stock": 0,
  "size": "XS"
}

### Authorization


### Login as admin

#POST localhost:8080/api/auth/login
#Content-Type: application/json
#
#{
#  "username": "admin@mail.com",
#  "password": "adminsecret"
#}
#> {% client.global.set("auth-token", response.body.token); %}
