### wszystkie

GET localhost:8080/api/products
authorization: Bearer {{auth-token}}

### podzielone na strony

GET localhost:8080/api/products?page=1&size=5
Authorization: Bearer {{auth-token}}

### wg categoryId

GET localhost:8080/api/products?categoryId=8
Authorization: Bearer {{auth-token}}

### wg subcategoryId

GET localhost:8080/api/products?subcategoryId=18
Authorization: Bearer {{auth-token}}

### wg size

GET localhost:8080/api/products?size=L
Authorization: Bearer {{auth-token}}

### wg stock niezerowy

GET localhost:8080/api/products/in-stock
Authorization: Bearer {{auth-token}}

### wg stock zerowy

GET localhost:8080/api/products/not-in-stock
Authorization: Bearer {{auth-token}}

### wg stock do zamowienia

GET localhost:8080/api/products/top-up-stock
Authorization: Bearer {{auth-token}}

### wg nazwy produktu

GET localhost:8080/api/products?productName=Marynarka
Authorization: Bearer {{auth-token}}

### wg rozmiaru i subkategorii

GET localhost:8080/api/products?size=L&subcategoryId=18
Authorization: Bearer {{auth-token}}

### wg Id produktu

GET localhost:8080/api/products/a0e25ff8-f3cd-4aef-917a-f2417d172c52
Authorization: Bearer {{auth-token}}

### wózek użytkownika

GET localhost:8080/api/cart
Authorization: Bearer {{auth-token}}

### zamówienia użytkownika

GET localhost:8080/api/orders
Authorization: Bearer {{auth-token}}

### dane zamówienie użytkownika

GET localhost:8080/api/orders/1
Authorization: Bearer {{auth-token}}

### Swagger API Docs

GET localhost:8080/v3/api-docs
